# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RideGR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RideGR

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Email'
 
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'	

  target 'RideGRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RideGRUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
